name: flutter_drawer_tab_host
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_redux: ^0.5.0
  intl: ^0.15.2
  shared_preferences: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fevicn.png




